server:
  port: 8082 # Puerto donde va correr el order service

spring: 
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/msv_orderdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expone todos los endpoints de Actuator
